// import "./globals.css";
// import SessionProviderWrapper from "./components/SessionProviderWrapper";

// export const metadata = {
//   title: "Task Assignment App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <SessionProviderWrapper>
//           <nav>
//             <a href="/">Home</a>
//             <a href="/register">Register</a>
//             <a href="/login">Login</a>
//             <a href="/admin">Admin</a>
//             <a href="/tasks">My Tasks</a>
//           </nav>

//           {children}
//         </SessionProviderWrapper>
//       </body>
//     </html>
//   );
// }


// import "./globals.css";
// import SessionProviderWrapper from "./components/SessionProviderWrapper";
// import { usePathname } from "next/navigation";


// export const metadata = {
//   title: "Task Assignment App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   const pathname = usePathname();
//   const showNavbar = pathname !== "/"; // Hide navbar on home page

//   return (
//     <html lang="en">
//       <body>
//         <SessionProviderWrapper>
//           {showNavbar && (
//             <nav className="bg-blue-500 text-white p-4 flex gap-4">
//               <a href="/">Home</a>
//               <a href="/register">Register</a>
//               <a href="/login">Login</a>
//               <a href="/admin">Admin</a>
//               <a href="/tasks">My Tasks</a>
//             </nav>
//           )}
//           {children}
//         </SessionProviderWrapper>
//       </body>
//     </html>
//   );
// }


import "./globals.css";
import SessionProviderWrapper from "./components/SessionProviderWrapper";
import Navbar from "./components/Navbar"; // ✅ Import the client-side Navbar

export const metadata = {
  title: "Task Assignment App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <Navbar /> {/* ✅ Navbar is now a separate client component */}
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
